### ISSUE TITLE
Protobuf update 1.27.0 breaks websocket updates

### ISSUE THREAD

**Issue by melanu1991** [centrifugal/centrifuge-swift#101]
When I have tried to use the new released protobuf 1.27.0 that broke for me any websocket updates due to I am receiving in the console a lot of [debug] messages like: connected -> reconnected and so on endless loop of this events. Any thought about this issue?

**Comment by FZambia** [comment]
Helo @melanu1991 

Unfortunate thing, looks like SwiftProtobuf is a massive release with tons of changes, including breaking behaviour changes.

Addressing in #102, works for me locally. Please check it out – if no objections/suggestions I'll proceed with release.

**Comment by melanu1991** [comment]
Thank you so much too! Well done!
