### ISSUE TITLE
Presence after migration from 0.4.6 -> 0.7.2

### ISSUE THREAD

**Issue by swilliams-intellum** [centrifugal/centrifuge-swift#103]
I am using the presence API to receive notifications that the list of present users has changed. As someone became present or absent my completion closure for the `subscription.presence` method would be called. After upgrading to 0.7.2 this no longer happens. It only gets called initially after first subscribing. 

```swift
subscription.presence(completion: { result in
            switch result {
            case .success(let presence):
                completion?(presence, nil)
```

Is this a bug or has the API changed in a way that I need to account for?

Note: the same thing happens on Android.

**Comment by swilliams-intellum** [comment]
Apologies! It is the `onJoin` and `onLeave` that are not being called.

**Comment by FZambia** [comment]
Hello @swilliams-intellum 

Yeah, may be the case that server is just not configured to send join/leave events to a channel - just having `"presence": true` is not enough. For latest Centrifugo version the config can look like https://centrifugal.dev/docs/server/presence#join-and-leave-events .

**Comment by swilliams-intellum** [comment]
Thanks! That did the trick.
