### ISSUE TITLE
Doesn't work with Carthage

### ISSUE THREAD

**Issue by danqing** [centrifugal/centrifuge-swift#14]
```
*** Skipped building centrifuge-swift due to the error:
Dependency "centrifuge-swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/centrifugal/centrifuge-swift/issues/new
```

Looking at the source, there's no xcodeproj file (other than the one for example), and so there's no target that builds the framework. I believe that's the reason.

**Comment by FZambia** [comment]
Hmm, I suppose it worked before... Will try to investigate this.

**Comment by danqing** [comment]
I'm pretty sure fixing this involves the following:

1. Create a .xcodeproj file for the framework itself (not for the example app) and add its files
2. Create a Cartfile in the root folder that lists the dependencies (protobuf, starscream)
3. Do `carthage update` and that will build the two dependencies. Add the resulting frameworks into .xcodeproj
4. Make sure the framework can build with the dependencies added

**Comment by FZambia** [comment]
I am not an iOS developer and diving into this seems a bit time-consuming. That's why some basic things are still missing here..

**Comment by danqing** [comment]
This is not important to me right now since I've transitioned to using SPM :)
