### ISSUE TITLE
Connection error event?

### ISSUE THREAD

**Issue by danqing** [centrifugal/centrifuge-swift#16]
I am debugging a connection issue and I noticed that there's no event whatsoever when the connection is not succeeding.

My code is almost the same as in README:

```swift
let client = CentrifugeClient(url: url, config: CentrifugeClientConfig(), delegate: CentrifugeDelegate())
client.setToken(self.token)
client.connect()
```

... where `CentrifugeDelegate` has the `onConnect` and `onDisconnect` methods.

What happens is that the code gets executed, it's not connected to the server (log_level=debug doesn't show anything), and neither of the two methods are called. Basically, nothing happens.

I think it is useful both for debugging and for notifying the users that there's some delegate method, error or something else that gets triggered when the initial connection fails.

**Comment by FZambia** [comment]
Thanks, I suppose we can add `onError` delegate method that will report connection errors like this.

**Comment by FZambia** [comment]
All protocol features existing at this point were supported in [0.5.0](https://github.com/centrifugal/centrifuge-swift/releases/tag/0.5.0).
