### ISSUE TITLE
CentrifugeSubscription syncQueue

### ISSUE THREAD

**Issue by NailxSharipov** [centrifugal/centrifuge-swift#24]
Write now each Subscription has its own sync queue. I guess it will be better if Subscription will be work on Client sync queue by two reasons:
- resource / performance issues, if you have they a lot. I my project I have at least 30 - 50 at some screens.  Most of the time this queues are do nothing. They only purpose is a sync mechanism.
- code can be look much simpler and easy for support.

**Comment by FZambia** [comment]
I suppose that overhead is relatively small, but in general I don't have any arguments against this refactoring.

**Comment by FZambia** [comment]
Fixed by https://github.com/centrifugal/centrifuge-swift/pull/50
