### ISSUE TITLE
Access to properties of `CentrifugeClientInfo`

### ISSUE THREAD

**Issue by leonovvalentin** [centrifugal/centrifuge-swift#30]
Method `presence(completion:)` in `CentrifugeSubscription` has completion block with parameter of type `[String: CentrifugeClientInfo]?`, but I can not use any property from `CentrifugeClientInfo` because it have `internal` access modifier.

Question is how should I use `CentrifugeClientInfo` object? Is it really needed to use `internal` instead of `public`?

**Comment by FZambia** [comment]
@leonovvalentin hello, must be public, yes:) Looks like you are the first who want to use it.

**Comment by FZambia** [comment]
Just released 0.0.6, thanks for pointing this!
