### ISSUE TITLE
implementation of Protobuf for Swift Encodable / Decodable

### ISSUE THREAD

**Issue by hnazari1990** [centrifugal/centrifuge-swift#34]
At the moment, the centrifuge-swift only support Protobuf protocol, I have an old Swift codebase with JSON protocol that uses Encodable/Decodable and Because it's too much work for me to change that, is it possible to encode/decode Protobuf with Encodable? Is there any library that implements Encodable and Decodable on Protobuf protocol?
Any suggestions would be helpful.

**Comment by FZambia** [comment]
@hnazari1990 hello, you can still send JSON with this library - since JSON payload can be easily transferred inside Protobuf frames. You don't need to encode your application data to Protobuf.

**Comment by FZambia** [comment]
Closing as no response from op
