### ISSUE TITLE
Invalid HTTP upgrade when try to connect

### ISSUE THREAD

**Issue by aytoku** [centrifugal/centrifuge-swift#37]
When I try to connect, I am always thrown into onDisconnect. I looked into the connect() and there I came across an error 308 and message "Invalid HTTP upgrade". Do u have any solutions ?

**Comment by antonselyanin** [comment]
AFAIK, a websocket connection is established via http UPGRADE command. Check if your webserver allows WS connections.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism
