### ISSUE TITLE
Accept offset and epoch in subscribe method

### ISSUE THREAD

**Issue by foresh9** [centrifugal/centrifuge-swift#47]
From here: [centrifugal/centrifugo/issues/446](https://github.com/centrifugal/centrifugo/issues/446)

It would be extra great if the centrifuge-swift client libraries could accept an offset and epoch right in subscribe method - automatically retrieving and playing back any messages missed afterwards.

**Comment by FZambia** [comment]
All protocol features existing at this point were supported in [0.5.0](https://github.com/centrifugal/centrifuge-swift/releases/tag/0.5.0)
