### ISSUE TITLE
Any plan to update to Starscream 4?

### ISSUE THREAD

**Issue by danqing** [centrifugal/centrifuge-swift#48]
As the topic says. Thanks!

**Comment by FZambia** [comment]
Hello, there was a pull request https://github.com/centrifugal/centrifuge-swift/pull/19, at that point Starscream 4 had several known problems.

Starscream not maintained well these days so I am not sure migration to v4 can give any benefit. Did you experience any problems with Starscream 3 which you aim to solve?

**Comment by danqing** [comment]
Not really but I remember seeing some ss 3 issues back in the day (before v4 came out), and just curious about the plan here.

**Comment by FZambia** [comment]
@fedulvtubudul opened a pr #53 to embed Starscream 3 for now till we find and migrate to a better alternative (which can take much more time). What do you think – is this viable for you?

**Comment by fedulvtubudul** [comment]
@FZambia yep, thanks! Recently we've done the same on [our fork](https://github.com/VLprojects/centrifuge-swift/commit/df14120f95e6689193395ca25d94dea58e123893) to integrate Centrifuge into a project that already uses SocketIO. So now we can return to upstream which is great.

**Comment by FZambia** [comment]
So CentrifugeSwift 0.4.2 now embeds Starscream 3 and does not have an external dependency to Starscream. I hope this is a temporary thing – but hard to say when we do the next step, as I said above – I am a bit worried about Starscream 4 state these days.

**Comment by FZambia** [comment]
I suppose next step here would be: use native URLSessionWebSocketTask if available and fallback to our embedded Starscream 3 fork for older devices. Appreciate help with this.

**Comment by FZambia** [comment]
Thanks to https://github.com/centrifugal/centrifuge-swift/pull/84 we now have an optional WS transport using URLSessionWebSocketTask. Will be part of next release.

**Comment by FZambia** [comment]
available in 0.7.0
