### ISSUE TITLE
The client fails to connect without an initial token

### ISSUE THREAD

**Issue by antonselyanin** [centrifugal/centrifuge-swift#70]
The client fails to connect without an initial token. 
Steps to reproduce:
1. Initialize `CentrifugeClient` with an empty token and a non-nil token getter.
2. Invoke `connect`

The client tries to get a token via the token getter but it fails to proceed because it simultaneously tries to connect with an empty token.

**Comment by FZambia** [comment]
The fix is part of 0.5.2 - many thanks!

**Comment by FZambia** [comment]
Found one more related problem - https://github.com/centrifugal/centrifuge-swift/commit/c41cea5f5b2b29051937a630a5677f86dd92a377 - will release 0.5.3 shortly
