### ISSUE TITLE
I received error

### ISSUE THREAD

**Issue by Sargis** [centrifugal/centrifuge-swift#75]
func onError(_ client: CentrifugeClient, _ event: CentrifugeErrorEvent){
        
}

about onError function, I get following error 

▿ CentrifugeError
  ▿ transportError : 1 element
    ▿ error : WSError
      - type : SwiftCentrifuge.ErrorType.protocolError
      - message : "{\"reason\":\"bad request\",\"reconnect\":false}"
      - code : 3003

Please help me try  to understand error:
Thanks

**Comment by FZambia** [comment]
Hello, do you know when it happens? On connect? In general, the simplest way is to look at server logs and logs should contain entry on INFO level about the reason of client's bad request.

Most often you can get error like this during connect if you have invalid token, or connecting without token and without connect proxy configured on server side.

**Comment by Sargis** [comment]
Thanks for response 
I get following logs from backend side 

{"level":"info","client":"ce6b4c25-7694-4b1a-8fe5-5f2266ebc15d","data":"n\b\u0015\"j\naeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNiJ9.qDnjxWXiYhViUWCG3yLVFFSaEreKicVSjCGU-QVa2M0\"\u0005swift","error":"invalid character '\\b' in literal null (expecting 'u')","user":"","time":"2022-11-24T12:16:17Z","message":"error decoding command"}
{"level":"debug","client":"ce6b4c25-7694-4b1a-8fe5-5f2266ebc15d","reason":"bad request","reconnect":false,"user":"","time":"2022-11-24T12:16:17Z","message":"closing client connection"}

**Comment by Sargis** [comment]
Hello
We have updated server version, and everything is work perfectly 

Thank you very much Alexander

**Comment by FZambia** [comment]
Ah, cool :) Welcome!
