### ISSUE TITLE
Delegate methods don't work

### ISSUE THREAD

**Issue by Medef** [centrifugal/centrifuge-swift#77]
Hi, I ran into a problem with how the delegate methods work. When I connect to the server, they don't work. I am immediately disconnected from the server without any logs.
Perhaps I am doing something wrong, so please help with this problem. I will be grateful for the answer
Code:
![Снимок экрана 2022-12-26 в 14 17 41](https://user-images.githubusercontent.com/40383119/209543078-5c7971c6-abdf-437e-9386-294fa41f8399.png)
![Снимок экрана 2022-12-26 в 14 17 57](https://user-images.githubusercontent.com/40383119/209543107-f8c270bb-109b-4b08-8ff6-1209b6643d46.png)
![Снимок экрана 2022-12-26 в 14 19 31](https://user-images.githubusercontent.com/40383119/209543252-6a9f3db6-1842-4531-8937-221d7e7a6965.png)

**Comment by FZambia** [comment]
Hello, it's impossible to help given this amount of information. Probably you will find the reason of disconnect in server logs. Also `onDisconnected` event should contain code and reason of disconnect – but I don't see it in the output you provided. I see you have `disconnected` line in the output - probably it comes from your disconnect function where you are printing `client.state` – so you manually call disconnect for some reason.

**Comment by Medef** [comment]
> Hello, it's impossible to help given this amount of information. Probably you will find the reason of disconnect in server logs. Also `onDisconnected` event should contain code and reason of disconnect – but I don't see it in the output you provided. I see you have `disconnected` line in the output - probably it comes from your disconnect function where you are printing `client.state` – so you manually call disconnect for some reason.

I don't know what the reason is, but my implementation above didn't want to work and what surprised me the most was that the delegate methods were not called. So I rewrote my service and now everything works correctly, the delegates work. I don't even know what could be the problem
![Снимок экрана 2022-12-26 в 16 39 38](https://user-images.githubusercontent.com/40383119/209554844-cfa08ed4-fb17-46e8-8b9b-706ecdb304cc.png)

**Comment by FZambia** [comment]
Hm, strange - but happens :) Looks like we can close this issue?

**Comment by Medef** [comment]
> Hm, strange - but happens :) Looks like we can close this issue?

Yep, u can close it, thanks :)
