### ISSUE TITLE
Use problem

### ISSUE THREAD

**Issue by rookieLeaves** [centrifugal/centrifuge-swift#9]
Dear Author：
     I found a few problems when using this project.
        1.Unsubscribe without going through the protocol callback
        2.Create a channel object multiple times, it will kill the app
      I am working on your demo.

**Comment by FZambia** [comment]
Hello, please provide steps and code to reproduce.

**Comment by rookieLeaves** [comment]
https://github.com/rookieLeaves/socket_demo.git

**Comment by rookieLeaves** [comment]
> Hello, please provide steps and code to reproduce.

https://github.com/rookieLeaves/socket_demo.git

3.Create a channel object multiple times, it will kill the app
connect ->  sub ->sub

**Comment by FZambia** [comment]
You need to handle duplicateSub exception in your code. Library allows to subscribe on the same channel only once.

Please give a more detailed description on each point - it will save a lot of my time to debug. Is your demo demonstrating problems? What should I do to reproduce them?

**Comment by rookieLeaves** [comment]
Channel subscription I have done special processing, but I still have a problem, that is, unsubscribe without going through the protocol callback
The following methods do not go：
 func onUnsubscribe(_ s: CentrifugeSubscription, _ e: CentrifugeUnsubscribeEvent) {
        print("unsubscribed from channel", s.channel)
 }

**Comment by puryagh** [comment]
hi
I fixed unsubscribe problem and new found bug on strong delegate of CentrifugeSubscriptionDelegate that causes client not deinited .
you can download fixed package from https://github.com/puryagh/centrifuge-swift and use it
😇

**Comment by FZambia** [comment]
@puryagh thanks, I will give more attention to fixing these problems very soon

**Comment by FZambia** [comment]
Fixed unsubscribe problem and made pull request #10

**Comment by FZambia** [comment]
Should be fixed in v0.0.3
